# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "ON")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "OFF")
SET(CPACK_BINARY_ZIP "OFF")
SET(CPACK_CMAKE_GENERATOR "Visual Studio 12")
SET(CPACK_COMPONENTS_ALL "Unspecified;headers;libraries;utilities")
SET(CPACK_COMPONENT_DEPENDENCIES_DESCRIPTION "Dependencies for this build of NetCDF-C")
SET(CPACK_COMPONENT_DOCUMENTATION_DESCRIPTION "The NetCDF-C user documentation.")
SET(CPACK_COMPONENT_HEADERS_DESCRIPTION "Header files for use with NetCDF-C")
SET(CPACK_COMPONENT_LIBRARIES_DESCRIPTION "The NetCDF-C Libraries")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_COMPONENT_UTILITIES_DESCRIPTION "The NetCDF-C Utilities")
SET(CPACK_GENERATOR "NSIS")
SET(CPACK_INSTALL_CMAKE_PROJECTS "D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc;netCDF;ALL;/")
SET(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/netCDF")
SET(CPACK_MODULE_PATH "D:/Development/op3d_active/netcdf-c-4.3.3.1/cmake/modules/")
SET(CPACK_NSIS_CONTACT "support-netcdf@unidata.ucar.edu")
SET(CPACK_NSIS_DISPLAY_NAME "NetCDF 4.3.3.1")
SET(CPACK_NSIS_DISPLAY_NAME_SET "TRUE")
SET(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL "ON")
SET(CPACK_NSIS_HELP_LINK "http://www.unidata.ucar.edu/netcdf")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_MENU_LINKS "http://www.unidata.ucar.edu/netcdf;Unidata Website;http://www.unidata.ucar.edu/netcdf/docs;NetCDF Stable Documentation;http://www.unidata.ucar.edu/netcdf/docs_rc;NetCDF Unstable Documentation")
SET(CPACK_NSIS_MODIFY_PATH "ON")
SET(CPACK_NSIS_PACKAGE_NAME "NetCDF 4.3.3.1")
SET(CPACK_NSIS_URL_INFO_ABOUT "http://www.unidata.ucar.edu/netcdf")
SET(CPACK_OUTPUT_CONFIG_FILE "D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "NetCDF Support <support-netcdf@unidata.ucar.edu>")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "netCDF built using CMake")
SET(CPACK_PACKAGE_FILE_NAME "netCDF-4.3.3.1-win32")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "netCDF 4.3.3.1")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "netCDF 4.3.3.1")
SET(CPACK_PACKAGE_NAME "netCDF")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Unidata")
SET(CPACK_PACKAGE_VERSION "4.3.3.1")
SET(CPACK_PACKAGE_VERSION_MAJOR "0")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "1")
SET(CPACK_RESOURCE_FILE_LICENSE "D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc/COPYRIGHT.txt")
SET(CPACK_RESOURCE_FILE_README "C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Templates/CPack.GenericWelcome.txt")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "ZIP")
SET(CPACK_SOURCE_IGNORE_FILES ";/expecttds3/;/nocacheremote3/;/nocacheremote4/;/special3/;D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc/*;/myhtml/*;/.svn/;my.*\\.sh;/.deps/;/.libs;/html/;.*\\.jar;.*\\.jdl;.*\\.sed;.*\\.proto;.*\\.texi;.*\\.example;Make0;/obsolete/;/unknown/;.*~")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "ON")
SET(CPACK_SYSTEM_NAME "win32")
SET(CPACK_TOPLEVEL_TAG "win32")
SET(CPACK_WIX_SIZEOF_VOID_P "4")
