# CMake generated Testfile for 
# Source directory: D:/Development/op3d_active/netcdf-c-4.3.3.1/nc_test4
# Build directory: D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc/nc_test4
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
ADD_TEST(nc_test4_run_grp_rename "bash" "-c" "export srcdir=D:/Development/op3d_active/netcdf-c-4.3.3.1/nc_test4;export TOPSRCDIR=D:/Development/op3d_active/netcdf-c-4.3.3.1;D:/Development/op3d_active/netcdf-c-4.3.3.1/msvc/nc_test4/run_grp_rename.sh")
ADD_TEST(nc_test4_tst_dims "/nc_test4_tst_dims")
SET_TESTS_PROPERTIES(nc_test4_tst_dims PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_dims2 "/nc_test4_tst_dims2")
SET_TESTS_PROPERTIES(nc_test4_tst_dims2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_dims3 "/nc_test4_tst_dims3")
SET_TESTS_PROPERTIES(nc_test4_tst_dims3 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_files "/nc_test4_tst_files")
SET_TESTS_PROPERTIES(nc_test4_tst_files PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_files4 "/nc_test4_tst_files4")
SET_TESTS_PROPERTIES(nc_test4_tst_files4 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_vars "/nc_test4_tst_vars")
SET_TESTS_PROPERTIES(nc_test4_tst_vars PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_varms "/nc_test4_tst_varms")
SET_TESTS_PROPERTIES(nc_test4_tst_varms PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_unlim_vars "/nc_test4_tst_unlim_vars")
SET_TESTS_PROPERTIES(nc_test4_tst_unlim_vars PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_converts "/nc_test4_tst_converts")
SET_TESTS_PROPERTIES(nc_test4_tst_converts PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_converts2 "/nc_test4_tst_converts2")
SET_TESTS_PROPERTIES(nc_test4_tst_converts2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_grps "/nc_test4_tst_grps")
SET_TESTS_PROPERTIES(nc_test4_tst_grps PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_grps2 "/nc_test4_tst_grps2")
SET_TESTS_PROPERTIES(nc_test4_tst_grps2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_compounds "/nc_test4_tst_compounds")
SET_TESTS_PROPERTIES(nc_test4_tst_compounds PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_compounds2 "/nc_test4_tst_compounds2")
SET_TESTS_PROPERTIES(nc_test4_tst_compounds2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_compounds3 "/nc_test4_tst_compounds3")
SET_TESTS_PROPERTIES(nc_test4_tst_compounds3 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_opaques "/nc_test4_tst_opaques")
SET_TESTS_PROPERTIES(nc_test4_tst_opaques PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_strings "/nc_test4_tst_strings")
SET_TESTS_PROPERTIES(nc_test4_tst_strings PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_strings2 "/nc_test4_tst_strings2")
SET_TESTS_PROPERTIES(nc_test4_tst_strings2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_interops "/nc_test4_tst_interops")
SET_TESTS_PROPERTIES(nc_test4_tst_interops PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_interops4 "/nc_test4_tst_interops4")
SET_TESTS_PROPERTIES(nc_test4_tst_interops4 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_interops6 "/nc_test4_tst_interops6")
SET_TESTS_PROPERTIES(nc_test4_tst_interops6 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_enums "/nc_test4_tst_enums")
SET_TESTS_PROPERTIES(nc_test4_tst_enums PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_coords "/nc_test4_tst_coords")
SET_TESTS_PROPERTIES(nc_test4_tst_coords PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_coords2 "/nc_test4_tst_coords2")
SET_TESTS_PROPERTIES(nc_test4_tst_coords2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_coords3 "/nc_test4_tst_coords3")
SET_TESTS_PROPERTIES(nc_test4_tst_coords3 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_vars3 "/nc_test4_tst_vars3")
SET_TESTS_PROPERTIES(nc_test4_tst_vars3 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_vars4 "/nc_test4_tst_vars4")
SET_TESTS_PROPERTIES(nc_test4_tst_vars4 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_chunks "/nc_test4_tst_chunks")
SET_TESTS_PROPERTIES(nc_test4_tst_chunks PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_chunks2 "/nc_test4_tst_chunks2")
SET_TESTS_PROPERTIES(nc_test4_tst_chunks2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_utf8 "/nc_test4_tst_utf8")
SET_TESTS_PROPERTIES(nc_test4_tst_utf8 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_fills "/nc_test4_tst_fills")
SET_TESTS_PROPERTIES(nc_test4_tst_fills PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_fills2 "/nc_test4_tst_fills2")
SET_TESTS_PROPERTIES(nc_test4_tst_fills2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_fillbug "/nc_test4_tst_fillbug")
SET_TESTS_PROPERTIES(nc_test4_tst_fillbug PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_xplatform "/nc_test4_tst_xplatform")
SET_TESTS_PROPERTIES(nc_test4_tst_xplatform PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_xplatform2 "/nc_test4_tst_xplatform2")
SET_TESTS_PROPERTIES(nc_test4_tst_xplatform2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_h_atts2 "/nc_test4_tst_h_atts2")
SET_TESTS_PROPERTIES(nc_test4_tst_h_atts2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_endian_fill "/nc_test4_tst_endian_fill")
SET_TESTS_PROPERTIES(nc_test4_tst_endian_fill PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_atts "/nc_test4_tst_atts")
SET_TESTS_PROPERTIES(nc_test4_tst_atts PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_t_type "/nc_test4_t_type")
SET_TESTS_PROPERTIES(nc_test4_t_type PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_cdm_sea_soundings "/nc_test4_cdm_sea_soundings")
SET_TESTS_PROPERTIES(nc_test4_cdm_sea_soundings PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_vl "/nc_test4_tst_vl")
SET_TESTS_PROPERTIES(nc_test4_tst_vl PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_atts1 "/nc_test4_tst_atts1")
SET_TESTS_PROPERTIES(nc_test4_tst_atts1 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_atts2 "/nc_test4_tst_atts2")
SET_TESTS_PROPERTIES(nc_test4_tst_atts2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_vars2 "/nc_test4_tst_vars2")
SET_TESTS_PROPERTIES(nc_test4_tst_vars2 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_files5 "/nc_test4_tst_files5")
SET_TESTS_PROPERTIES(nc_test4_tst_files5 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_files6 "/nc_test4_tst_files6")
SET_TESTS_PROPERTIES(nc_test4_tst_files6 PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_sync "/nc_test4_tst_sync")
SET_TESTS_PROPERTIES(nc_test4_tst_sync PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_h_strbug "/nc_test4_tst_h_strbug")
SET_TESTS_PROPERTIES(nc_test4_tst_h_strbug PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_h_refs "/nc_test4_tst_h_refs")
SET_TESTS_PROPERTIES(nc_test4_tst_h_refs PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_h_scalar "/nc_test4_tst_h_scalar")
SET_TESTS_PROPERTIES(nc_test4_tst_h_scalar PROPERTIES  FOLDER "tests/")
ADD_TEST(nc_test4_tst_rename "/nc_test4_tst_rename")
SET_TESTS_PROPERTIES(nc_test4_tst_rename PROPERTIES  FOLDER "tests/")
